name: "Push flake inputs to Cachix"
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2.4.0
      - name: "Install Nix"
        uses: cachix/install-nix-action@v20
      - name: "Install Cachix"
        uses: cachix/cachix-action@v12
        with:
          name: pdalpra
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: "Push flake inputs to Cachix"
        run: "nix flake archive --json | jq -r '.path,(.inputs|to_entries[].value.path)' | cachix push pdalpra"