---
name: Home Manager configuration
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
      - name: Install Nix
        uses: nixbuild/nix-quick-install-action@v25
      - name: Install Cachix
        uses: cachix/cachix-action@v12
        with:
          name: pdalpra
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: Setup cache
        uses: DeterminateSystems/magic-nix-cache-action@v2
      - name: Build Home Manager configuration
        run: nix build ".#homeConfigurations.pdalpra.activationPackage"
