---
name: Build ISO
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Nix
        uses: cachix/install-nix-action@v25
      - name: Install Cachix
        uses: cachix/cachix-action@v14
        with:
          name: pdalpra
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
          skipPush: true
      - name: Setup cache
        uses: DeterminateSystems/magic-nix-cache-action@v3
      - name: Build ISO
        run: |
          derivation=".#nixosConfigurations.iso.config.system.build.isoImage"
          cp -R "$(nix build $derivation --print-out-paths)/iso" .
      - name: Upload to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --follow-symlinks
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_NIX_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: eu-west-1
          SOURCE_DIR: iso
          DEST_DIR: iso
