---
name: Lint
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
      - name: Install Nix
        uses: cachix/install-nix-action@v20
      - name: Check that all sources are properly formatted
        run: |-
          nix develop -c lint-all
