---
name: Lint
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Nix
        uses: cachix/install-nix-action@v25
      - name: Install Cachix
        uses: cachix/cachix-action@v14
        with:
          name: pdalpra
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
          skipPush: true
      - name: Setup cache
        uses: DeterminateSystems/magic-nix-cache-action@v3
      - name: Check that all sources are properly formatted
        run: |-
          nix develop -c lint-all
