name: "NixOS configuration"
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2.4.0
      - name: "Install Nix"
        uses: cachix/install-nix-action@v20
      - name: "Install Cachix"
        uses: cachix/cachix-action@v12
        with:
          name: pdalpra
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: "Build NixOS configuration"
        run: "nix build \".#nixosConfigurations.vm.config.system.build.toplevel\""